### ISSUE TITLE
JavaGradleWorkflow fails with Gradle <3.5; Cannot convert the provided notation to a File or URI

### ISSUE THREAD

**Issue by davidmc24** [aws/aws-lambda-builders#137]
**Description:**

When I run `sam build` on my Java project with Gradle 3.4.1, it always fails.
This appears to be due to https://github.com/awslabs/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/java_gradle/resources/lambda-build-init.gradle#L18 setting the project `buildDir` property to a `Path`, when it isn't prepared for it.  Adding `.toFile()` to this line appears to fix the problem.

It appears that Gradle 3.5+ support resolving `Path` values.

**Steps to reproduce the issue:**

1. `sam init --runtime java8 --dependency-manager gradle --name gradlebuildtest`
2. `cd gradlebuildtest/`
3. `(cd HelloWorldFunction && sdk use gradle 3.4.1 && gradle wrapper) && sam build`

**Observed result:**

```

Using gradle version 3.4.1 in this shell.
:wrapper

BUILD SUCCESSFUL

Total time: 1.31 secs
Building resource 'HelloWorldFunction'
Running JavaGradleWorkflow:GradleBuild

Build Failed
Error: JavaGradleWorkflow:GradleBuild - Gradle Failed: FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'HelloWorldFunction'.
> Cannot convert the provided notation to a File or URI: /var/folders/p1/w3tg9xz54lj_4xgwj60tffb126v92f/T/tmptseldu67/4abbb2503507efca0fbeaf9d14459fc8cdd6af90/build.
  The following types/formats are supported:
    - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
    - A String or CharSequence URI, for example 'file:/usr/include'.
    - A File instance.
    - A URI or URL instance.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
mac-dcarr:gradlebuildtest dcarr$
```

**Expected result:**

```
mac-dcarr:gradlebuildtest dcarr$ (cd HelloWorldFunction && sdk use gradle 5.6.3 && gradle wrapper) && sam build

Using gradle version 5.6.3 in this shell.

BUILD SUCCESSFUL in 727ms
1 actionable task: 1 executed
Building resource 'HelloWorldFunction'
Running JavaGradleWorkflow:GradleBuild
Running JavaGradleWorkflow:CopyArtifacts

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Package: sam package --s3-bucket <yourbucket>

mac-dcarr:gradlebuildtest dcarr$
```

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Scripts were run on Mac OS X 10.14.6, and use https://sdkman.io/ for Gradle version management.

**Comment by awood45** [comment]
To help understand background on this, is there a reason you cannot use a newer version of Gradle?

**Comment by davidmc24** [comment]
A particularly good reason?  No. The reality is that the project I first encountered this in is one that hasn’t had updates of any kind in a few years and updating to a modern version of Gradle would require enough changes, between new syntax, plugin updates, and so on, that it isn’t trivial.

**Comment by davidmc24** [comment]
I won’t be upset if you close this as “won’t fix”. It’s an old enough version that it would be reasonable to decide not to invest in supporting it.

**Comment by mndeveci** [comment]
Hi @davidmc24 ,

I've checked Gradle's plan for marking any release as EOL. And they mention that, once a new release comes out, the older one is marked as EOL.

> After a final release, the Gradle team may create additional patch releases that are intended to replace the previous final release due to an important bugfix or regression. For instance, Gradle 5.2.1 replaces the Gradle 5.2 release. Once a release candidate has been made, all feature development moves on to the next release. As such, each Gradle release causes the previous release to become end-of-line (EOL) and that release will not receive any new bugfixes or feature backports.

https://docs.gradle.org/current/userguide/feature_lifecycle.html#eol_support

For that reason, I am going to resolve this issue for now. Please let us know if we can improve anything else for java/gradle workflows.
