### ISSUE TITLE
Please add an example for Rust lambda runtime

### ISSUE THREAD

**Issue by brainstorm** [aws/aws-lambda-builders#167]
I would switch to this anytime (and away from serverless.com bloat) :)

**Comment by sriram-mv** [comment]
there is now a makefile builder workflow that can be used directly. https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-custom-runtimes.html

**Comment by brainstorm** [comment]
Thanks much for the pointer @sriram-mv! I would totally endorse https://github.com/awslabs/aws-lambda-builders/pull/174 from @softprops though, his PR makes integrating with AWS SAM effortless via Cargo (native Rust Makefile-equivalent).

**Comment by brainstorm** [comment]
More context into the "state of the SAM+lambda nation" in Rust for casual readers of this issue in case you are left wondering how to have a good SAM environment for Rust, hope it helps, I'll continue investigating how to put this thing together ;)

https://github.com/awslabs/aws-lambda-rust-runtime/pull/247/files#r488364611 ... and https://github.com/aws/aws-lambda-builders/pull/174#issuecomment-693208025
https://github.com/rimutaka/lambda-debug-proxy

**Comment by brainstorm** [comment]
Nevermind, the AWS Rust team is doing a great job with `cargo-lambda`, SAM is not strictly needed anymore, AFAICT.
