### ISSUE TITLE
Create a new action that can run workflows written in other programming languages

### ISSUE THREAD

**Issue by sanathkr** [aws/aws-lambda-builders#17]
**Description:**
To implement Javascript builder workflows, we need to an action that can invoke `node build.js` on the  build.js script that we will write. This is a common pattern for other programming languages too (java+maven, golang dotnet etc). In this task, we will create a new built-in Action that can help run builders implemented in other languages by spawning processes.

**Comment by jfuss** [comment]
Currently we are still tied to Python build workflows and have expanding to support things like this through the Makefile builder. 

Given the low +1 and Makefile as an alternative, I am opting to close this. However, feel free to re-open or create a new request (and link to this) if anyone in the community still would like something like this.
