### ISSUE TITLE
Python: Extend and/or override EXCLUDED_FILES

### ISSUE THREAD

**Issue by milesgranger** [aws/aws-lambda-builders#185]
### Describe your idea/feature/enhancement

It appears [the EXCLUDED_FILES is hardcoded.](https://github.com/awslabs/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/python_pip/workflow.py#L21)

It would be delightful if this could be extended/modified. I have many files and directories which are ignored by my own `.gitignore` but these continue to be included in the build directory by SAM. (`build/`, `.eggs/`, `.ipython/`, `.ipynb_checkpoints/`, `dist/`, `package.json`, `package-lock.json`, etc, etc)

Then there are files that shouldn't be ignored by git but should be ignored during the build such as a `tests` directory.

Furthermore, I don't actually want to ignore `.git/` b/c I use [setuptools-scm](https://pypi.org/project/setuptools-scm/) to control versioning with git, and during the build that fails because it has no git context.

### Proposal

Add configuration ability to override or extend with existing `.gitignore` or with own list, ie a `.samignore` file

**Comment by carpnick** [comment]
This needs to be exposed in AWS SAM to support other tools like - the AWS cfn tool set. - IE - https://github.com/aws-cloudformation/cloudformation-cli-python-plugin

Directly related to this issue - https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/247

**Comment by HWiese1980** [comment]
Has this feature been implemented? I'm running into the same problem with a python project that contains big virtual environments that I'd like to exclude.

**Comment by festusyuma** [comment]
> at contains bi

Hi, Have you had any luck with this issue, I have some symlinks in my project node_modules/.bin and I am unable to run sam build --use-container cos it keeps trying to copy the symlinks and end up with errors like this

FileNotFoundError: [Errno 2] No such file or directory: '***/backend/node_modules/.bin/ts-node'

**Comment by mildaniel** [comment]
Created a separate issue to consolidate the discussion for include/exclude functionality https://github.com/aws/aws-lambda-builders/issues/516.
