### ISSUE TITLE
Path resolution for runtime: nodejs12.x of binary: npm was not successful

### ISSUE THREAD

**Issue by keyboardDrummer** [aws/aws-lambda-builders#190]
**Description:**

I'm running SAM CLI as a child process of another process that's running in a non-interactive shell without environment variables, and when calling `sam invoke local` I get the message `Path resolution for runtime: nodejs12.x of binary: npm was not successful`. When running `sam invoke local` on this machine in an interactive terminal it works fine. I'd like to understand what aws-lambda-builders needs at minimum to do it's path resolution. Does npm need to be findable from the path? I've tried to uninstall npm on my machine but it seems like `sam invoke local` was still succeeding.

**Steps to reproduce the issue:**
1.
2.
3.

**Observed result:**

**Expected result:**

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

**Comment by CoshUS** [comment]
@keyboardDrummer Lambda builder needs nodejs12.x binary to be added in the PATH environment variable to build the project. Once the project is built, `sam local invoke` will use a docker image with npm to run. In such case, npm does not need to be installed to run `sam local invoke`.

**Comment by vilunet** [comment]
I am having the same issue when running SAM CLI in Jenkins
