### ISSUE TITLE
Maven dependencies are copied without considering duplicate artifactIds

### ISSUE THREAD

**Issue by lausdahl** [aws/aws-lambda-builders#194]
**Description:**

The java maven builder does not handle artefacts which shares the same artefactId but under different group Ids which results in classes missing the the class path after dependencies are copied. See for a full example: https://github.com/aws/aws-sam-cli/issues/2192

**Steps to reproduce the issue:**
Please see https://github.com/aws/aws-sam-cli/issues/2192 which has a full example

**Observed result:**
artefacts are overriden if they share the same artefact id
**Expected result:**
all artefacts unique

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

**Comment by mndeveci** [comment]
Looking at attached issues, the problem seems to be closed. Resolving this issue.
