### ISSUE TITLE
--production flag has no effect for `npm install`

### ISSUE THREAD

**Issue by mhart** [aws/aws-lambda-builders#200]
As specified here:

https://github.com/aws/aws-lambda-builders/blob/8ee704eebed7c63dce8b66592fac9c59d07b2120/aws_lambda_builders/workflows/nodejs_npm/actions.py#L108

`--production` is only useful for `npm ci` – it does nothing for `npm install` as far as I can tell:

https://docs.npmjs.com/cli/install

Related: https://github.com/aws/aws-sam-cli/issues/2269

**Comment by mhart** [comment]
Actually, reading through the docs, it does mention `--production`. I'm seeing strange behavior with npm 6.14.8 and node v12.18.4 where it's not respecting it. May be a bug in npm? Or something in my setup?

**Comment by mhart** [comment]
Suspect this may be the cause: https://github.com/npm/cli/issues/1113

Closing, sorry for the noise!

**Comment by anthony-tietjen-navex** [comment]
Looks like it might be more of a dependency thing. If I put mocha in devDependencies, then I get about 14 folders in the node_modules folder. But if I move mocha to the dependencies, then I get about 100 folders in node_modules.
