### ISSUE TITLE
Ignore files/folders for CustomMakeWorkflow

### ISSUE THREAD

**Issue by huanghe73** [aws/aws-lambda-builders#227]
**Description:**

When use CustomMakeWorkflow, SAM copies all files except (".aws-sam", ".git"). The source code folder would include `node_modules` and other files that we generally do not want to copy when using CustomMakeWorkflow, since the purpose of CustomMakeWorkflow is to build all these by myself.  Copying these files, when the project is large, takes significant time, especially if you frequently invoke locally to debug and/or if you are using `--use-container` flag. 

**Steps to reproduce the issue:**
1. in `template.yaml`, under lambda function section, use:
```yaml
  Metadata:
      BuildMethod: makefile
```
2. Create a valid `Makefile`
3. run `sam build`

**Observed result:**

All files and folders except (".aws-sam", ".git") are copied

**Expected result:**

Provide a way to ignore files and folders.

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Windows 10 WSL 2

**Suggestion**

Create a file called `.samignore` under the source folder and add/change below lines in file `aws-sam-cli\1.18.1\libexec\lib\python3.8\site-packages\aws_lambda_builders\workflows\custom_make\workflow.py`

```python
        samignore_file = f'{source_dir}/.samignore'
        lines = []
        if os.path.exists(samignore_file):
            with open(samignore_file, 'r') as f:
                lines = list(filter(lambda s: len(s) > 0 and s[0] != '#', [l[0:-1] if l[-1] == '\n' else l for l in f.readlines()]))
        excluded_files = list(self.EXCLUDED_FILES) + lines

        self.actions = [CopySourceAction(source_dir, scratch_dir, excludes=excluded_files), make_action]
```

**Comment by huanghe73** [comment]
I have changed my workflow and do not need this now. Thanks

**Comment by f-lombardo** [comment]
I know that  @huanghe73 closed this issue, but I think it's still an interesting feature, as it could solve also this issue [#3371](https://github.com/aws/aws-sam-cli/issues/3371)
