### ISSUE TITLE
Fix go.116 build issues.

### ISSUE THREAD

**Issue by sriram-mv** [aws/aws-lambda-builders#228]
**Go 1.16 Build Issues**

Go 1.16 introduced a breaking change with go build no longer being allowed to change/create go.mod and go.sum files by default.

https://golang.org/doc/go1.16

**Steps to reproduce the issue:**
1. Install Go 1.16
2. Create Go based init project through AWS SAM CLI
3. sam build

**Observed result:**
```
Running GoModulesBuilder:Build
Error: GoModulesBuilder:Build - Builder Failed: go: github.com/aws/aws-lambda-go@v1.13.3: missing go.sum entry; to add it:
	go mod download github.com/aws/aws-lambda-go
```

**Expected result:**

```
Building codeuri: hello-world/ runtime: go1.x metadata: {} functions: ['HelloWorldFunction']
Running GoModulesBuilder:Build

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided
```

**Comment by sriram-mv** [comment]
The workaround is to be able to set GOFLAGS such that editing of the go.sum or go.mod is allowed.

```
go env -w GOFLAGS="-mod=mod"
```

Allows for this.


The more holistic fix is to make sure that Lambda builders is able to do this automatically within the scope of the command by detecting the go version.

**Comment by aahung** [comment]
We fixed this issue from the app template side: https://github.com/aws/aws-sam-cli-app-templates/pull/99
I think we don't need to do anything in workflow.
