### ISSUE TITLE
Using from other languages

### ISSUE THREAD

**Issue by borgoat** [aws/aws-lambda-builders#235]
It's pretty nice that this library is provided with a CLI exposing a JSON-RPC interface with its functionality!

I ended up writing a wrapper since I needed to have this logic embedded in some software written in Go: https://github.com/borgoat/lambda-builders-go

It was a fairly smooth experience, although I had to look a bit at the internals to figure everything out.

Would it be useful if I opened a merge request:

1. briefly describing how to write such wrappers
2. creating a list of wrappers for other languages

and if so, it just go to the README? Or the [DESIGN DOCUMENT](https://github.com/aws/aws-lambda-builders/blob/develop/DESIGN.md)

Thanks!

**Comment by mgrandis** [comment]
@borgoat
This looks like a nice idea!
The DESIGN doc already has some info about the JSON RPC interface so I would go with this one for the wrapper documentation. 
We could then update the README with something akin to `If you are a developer willing to contribute or interested in earning more about the JSON RPC interface, read the DESIGN document...`
We are still evaluating how to list the community developed wrappers so please don't include these in your doc for now.

**Comment by borgoat** [comment]
Thanks for the feedback @mgrandis !

I have opened #242 with some initial thoughts

**Comment by mgrandis** [comment]
PR has been merged, thanks!
