### ISSUE TITLE
Python validation should try looking for `pythonX.Y` executable

### ISSUE THREAD

**Issue by sylveon** [aws/aws-lambda-builders#241]
**Description:**

When I work on AWS Lambdas, I need to use Python 3.6, 3.7 or 3.8 because those are the only supported versions, but my local global Python install is on 3.9. The binary validation can't find a Python 3.7 installation even though it is available as `python3.7` on the PATH.

**Steps to reproduce the issue:**
*Note: those are Windows specific because it's my main dev machine, but one could easily get something similar on a recent enough Linux distro.*
1. Install Python 3.9 from the Windows Store: https://www.microsoft.com/store/productId/9P7QFQMJRFP7
2. Install Python 3.7 from the Windows Store: https://www.microsoft.com/store/productId/9NJ46SX7X90P
3. In a CLI, observe that `python --version` and `python3 --version` gives Python 3.9, but `python3.7 --version` correctly yields Python 3.7.
4. Run something which invokes binary validation, for example `sam build`.

**Observed result:**
```
Error: PythonPipBuilder:Validation - Binary validation failed for python, search for python in following locations  : ['C:\\Users\\Sylveon\\AppData\\Local\\Microsoft\\WindowsApps\\python.EXE'] which did not satisfy constraints for runtime: python3.7. Do you have python for runtime: python3.7 on your PATH?
```

**Expected result:**
The binary validation should attempt to find `python3.7` in the PATH, and try this as an alternative if it exists and `python` did not give a suitable version.

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Windows 10, version 19043.1023
SAM CLI, version 1.23.0

**Comment by mgrandis** [comment]
Hi @sylveon,
As a workaround, have you considered using [pyenv](https://github.com/pyenv-win/pyenv-win)?
It allows switching between different Python versions and also creating virtual environments to avoid mixing your dependencies.

**Comment by sylveon** [comment]
I'm not mainly a Python dev so pyenv is more management overhead that I don't really want. Plus, the Windows Store version has benefits that pyenv does not bring, like automatic updates between minor versions and clean uninstalls.

**Comment by sriram-mv** [comment]
Are you seeing this behavior on Linux/MacOS as well? I just tested this on mac with a python3.7 on the PATH, while python --version was 3.8.8 and the build worked as specified when building a python3.7 app.

https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/path_resolver.py#L12

I will test this on windows next.

**Comment by sylveon** [comment]
It does seem like it works on Linux. I don't own an Apple device to try there.

**Comment by sriram-mv** [comment]
I retried this on powershell on a windows system. I had python3.7 and python3.8 installed side by side through choco.

I was able to build by changing the runtime within the python template from 3.7 to 3.8, I changed it to 2.7 and saw an error as expected.

```
Build Failed
Error: PythonPipBuilder:Validation - Binary validation failed for python, searched for python in following locations  : ['C:\\Python37\\python.EXE', 'C:\\Python38\\python.EXE', 'C:\\Python39\\python.EXE'] which did not satisfy constraints for runtime: python2.7. Do you have python for runtime: python2.7 on your PATH?
```

**Comment by jfuss** [comment]
Is this still occurring? Seems like it is working as expected reading https://github.com/aws/aws-lambda-builders/issues/241#issuecomment-890591212

**Comment by jfuss** [comment]
Closing given no response.
