### ISSUE TITLE
feature request: Option to preserve parent folder in CodeUri

### ISSUE THREAD

**Issue by heitorlessa** [aws/aws-lambda-builders#283]
**Description:**

For Python applications, it'd be ideal to have a flag in `sam build` to preserve the parent folder in CodeUri when building and copying artifacts to $ARTIFACTS_DIR.

This will enable Python developers to keep their layout for modules like we do elsewhere:

**Ideal**
```shell
.
├── loyalty
│   └── __init__.py
│   └── aggregate
│       ├── __init__.py
│       └── app.py
│   └── get
│       ├── __init__.py
│       └── app.py
│   └── ingest
│       ├── __init__.py
│       └── app.py
│   └── shared
│       ├── __init__.py
│       ├── constants.py
│       ├── functions.py
│       ├── models.py
│       └── storage.py
├── template.yaml
└── tests
    ├── conftest.py
    ├── events
    │   ├── aggregate_insert_event.json
    │   ├── get_event.json
    │   └── ingest_event.json
    ├── storage
    │   ├── __init__.py
    │   └── test_dynamodb.py
    └── unit
        ├── __init__.py
        ├── test_aggregate.py
        ├── test_get_loyalty_points.py
        └── test_ingest.py
```

**Template**

```yaml
...
  IngestFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ServerlessAirline-IngestLoyalty-${Stage}
      CodeUri: loyalty
      Handler: loyalty.ingest.app.lambda_handler
```

**Import line as well as tests**

```python
from loyalty.shared.models import LoyaltyPoint, LoyaltyPointAggregate
from loyalty.shared.storage import FakeStorage, DynamoDBStorage
...
```

To workaround this issue, I have to create another folder `src` to get the intended result[1], but this creates other problems in PYTHONPATH which I need to adjust in my IDE and tools later. Alternatively, I could use `BuildMethod: makefile` in SAM, but then I to lose `dedup` functionality.

**Steps to reproduce the issue:**
1. Use `loyalty` as `CodeUri`
2. Run `sam build`

**Observed result:** `loyalty` parent folder will not be copied over but its contents

**Expected result:** A flag to ensure folder in `CodeUri` is preserved when building artifacts, e.g. `--preserve-, or perhaps respect `folder` vs `folder/`.

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)** Mac

**Implementation in question that deliberately removes the parent folder**: https://github.com/aws/aws-lambda-builders/blob/41804217a18ff47cce5b62eff5cf884a7f81a0c5/aws_lambda_builders/utils.py#L16

---

[1] Current layout to ensure loyalty folder is copied over (`CodeUri: src`):

```shell
.
├── src
│   └── loyalty
│       ├── __init__.py
│       ├── aggregate
│       │   ├── __init__.py
│       │   └── app.py
│       ├── get
│       │   ├── __init__.py
│       │   └── app.py
│       ├── ingest
│       │   ├── __init__.py
│       │   └── app.py
│       └── shared
│           ├── __init__.py
│           ├── constants.py
│           ├── functions.py
│           ├── models.py
│           └── storage.py
├── template.yaml
└── tests
    ├── conftest.py
    ├── events
    │   ├── aggregate_insert_event.json
    │   ├── get_event.json
    │   └── ingest_event.json
    ├── storage
    │   ├── __init__.py
    │   └── test_dynamodb.py
    └── unit
        ├── __init__.py
        ├── test_aggregate.py
        ├── test_get_loyalty_points.py
        └── test_ingest.py
```

**Comment by hoffa** [comment]
Thanks for raising this! I'll close this ticket in favor of https://github.com/aws/aws-sam-cli/issues/3285.

**Comment by heitorlessa** [comment]
Thanks a lot Chris - wasn’t entirely sure if this belonged here given the
implementation or there.
