### ISSUE TITLE
`JavaMavenWorkflow:MavenCopyDependency` does not copy `runtime` dependencies

### ISSUE THREAD

**Issue by saraiyakush** [aws/aws-lambda-builders#311]
**Description:**

I am using `sam` to build and package my Java Maven project and I see that the `runtime` dependencies are not included as part of the target `lib` directory.

I have a dependency that needs to be used as `runtime` only and due to this, my application does not work as expected because sam build does not include these dependencies.

I also checked `this` repo's DESIGN.MD file
https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/java_maven/DESIGN.md
and it also specifies that the MavenCopyDependency step internally calls `mvn clean dependency:copy-dependencies -DincludeScope=compile`

**Steps to reproduce the issue:**
1. Add a dependency in `pom.xml` and scope it as `runtime`
2. Run `sam build`
3. Verify that `.aws-sam/build/Function/lib` does not include the dependency

**Expected result:**
The copy dependecies command should include the `runtime` dependencies.

**Comment by mndeveci** [comment]
We've released some changes recently, which should address the issue here. Please let us know if you still experience any issues by commenting in SAM CLI announcement issue: https://github.com/aws/aws-sam-cli/issues/3639
