### ISSUE TITLE
Custom builder should not copy source files to temp folder

### ISSUE THREAD

**Issue by zhuhaow** [aws/aws-lambda-builders#328]
Currently, the custom builder would copy the whole source code in `CodeUri` to a temp folder and run `make` there, causing https://github.com/aws/aws-sam-cli/issues/3371, https://github.com/aws/aws-sam-cli/issues/3350, https://github.com/aws/aws-sam-cli/issues/3093, https://github.com/aws/aws-sam-cli/issues/2688, to name a few.

But consider this:

1. The build process is already fully customized and all functions are built sequentially by default, the user can already control the building process so they won't need `sam` to provide a clean build env for them in ANY case. If they want to run the build in a new snapshot folder, they can do it themselves.
2. There is no "clean" build env. The project folder always contains a lot of build artifacts, caches, and other stuff that we want to put into ".gitignore". By copying them, the temp build env is not really clean anyway, unless the user cleans them manually before running `sam build`, which leads to 3.
3. If the project can not be built without a "clean" env, the user should clean the project in `Makefile`, the `sam` cannot do it for them anyway.

However, copying the source code not only takes a lot of time but makes incremental building almost impossible since the build happens in a temp folder.

I'm seconding https://github.com/aws/aws-sam-cli/issues/2655, but it should not be a feature, but a bug to fix. We may need a flag to guard this change but that's only for backward compatibility and building without copy should be the default behavior.

**Comment by zhuhaow** [comment]
It would be awesome this can be improved. Currently, I’m maintaining my own fork which is a pain

**Comment by mndeveci** [comment]
Thanks for the recommendation @zhuhaow 

The request makes sense, but we still need to maintain backward compatibility. For that reason, this could be tied into a flag in SAM CLI so that it won't be using TMP folder everytime it builds.

I tagged this issue with so that our PMs can take a look at it.

**Comment by torresxb1** [comment]
Closing so that we can track in the above issue (`Feature request: Build in source`). There's multiple open issues relating to similar problems, so we want to have a central place to track.
