### ISSUE TITLE
Golang with confluent Kafka library Sam build issue.

### ISSUE THREAD

**Issue by Venkat2382** [aws/aws-lambda-builders#349]
Hi, we use golang version 1.17 with confluent Kafka library. This will not allow cross arch compiling.
When I build the code via Sam build using .yaml file we see errors in build specific to this one lambda function. We use gitlab cicd pipeline. We baked our own docker image with golang.alpine and installed Sam cli and we do Sam build in our pipeline. After research it seems we need the -tags musl parameter of part of go build command. How to pass this parameter to go build command via Sam build? Is it even possible? We don't want to go the route of creating a docker image and using imageuri.

Please advice. TIA!!!

**Comment by Venkat2382** [comment]
Thanks!! @mildaniel . Can you please give me some samples of makefile. How it can be used to resolved go build.
Can you please provide more details.

**Comment by mndeveci** [comment]
Hi @Venkat2382 ,

You can read more about Makefile build in this documentation page; https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-custom-runtimes.html

Please let us know if you need further information.

Thanks!

**Comment by mingkun2020** [comment]
Closing. Feel free to reopen if there is more information on this issue.
