### ISSUE TITLE
Add support for SourcesContent option in esbuild builds

### ISSUE THREAD

**Issue by santiperone** [aws/aws-lambda-builders#438]
When dealing with bundled code it usually comes in handy to have the ability to keep track of where exceptions are being thrown in your code, which can be achieved by enable SourceMaps upon building. However, this creates a map file that includes all the original, untranspiled code, which is not always neccessary. Having the ability to disable SourcesContent would make your overall lambda size smaller (thus reducing start times) while still allowing to keep track of your original source code in an error stack.

**Comment by mildaniel** [comment]
Good call @santiperone. I'll look into adding this in.

**Comment by mildaniel** [comment]
This has been added. Try updating to the latest version of AWS SAM CLI and report back if there are any issues!
