### ISSUE TITLE
Bug: JavaGradleWorkflow not respecting gradlew with --use-container

### ISSUE THREAD

**Issue by wiwa5606** [aws/aws-lambda-builders#641]
### Description:
SAM does not download/use the Gradle wrapper when building Gradle function

### Steps to reproduce:
We are passing credentials through an embedded `gradle.properties` file in the build image that we are using. Our CodeURI was set to `IAPIHealthCheckServiceFn`.
The project file structure is as follows, attempting to replicate [this](https://github.com/aws/aws-sam-cli-app-templates/tree/master/java11/hello-gradle/%7B%7Bcookiecutter.project_name%7D%7D/HelloWorldFunction):

```
IAPIHealthCheckServiceFn
.
├── IAPIHealthCheckServiceFn
│   ├── build.gradle
│   ├── gradle
│   │   └── wrapper
│   │       ├── gradle-wrapper.jar
│   │       └── gradle-wrapper.properties
│   ├── gradle.properties
│   ├── gradlew
│   ├── gradlew.bat
│   ├── settings.gradle
│   └── src
├── README.md
├── dev_template.yaml
├── int_template.yaml
├── scr-input.sh
└── sonar-project.properties
```

The structure for `Project A` [here](https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/java_gradle/DESIGN.md#challenges) yield worse results, the build process fails to find the `IAPIHealthCheckServiceFn` folder. Note CodeURI was updated to `.` in this case:

```
.
├── README.md
├── build.gradle
├── dev_template.yaml
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradle.properties
├── gradlew
├── gradlew.bat
├── int_template.yaml
├── scr-input.sh
├── settings.gradle
├── sonar-project.properties
└── src
```

### Observed result:
When we execute `sam build`, we see that SAM is using the Gradle embedded in the docker image, (6.2.2), instead of the version configured in gradle-wrapper.properties, (8.2).
![image](https://github.com/aws/aws-lambda-builders/assets/112511907/7fd30d0f-ff22-4e09-94d9-73a318411f6a)

### Expected result:
`sam build` should use `gradlew` and use gradle version 8.2

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.84.0
3. AWS region: us-west-2

**Comment by mildaniel** [comment]
Hey @wiwa5606, can you try updating to the latest version of SAM CLI and seeing if the issue still exists?

**Comment by wiwa5606** [comment]
Hey there, same behavior on 1.116.0

**Comment by mildaniel** [comment]
@wiwa5606, are you able to provide a minimal app with which you're seeing this issue? I've tried to reproduce starting from a hello-world Java gradle template, with various version of Java and gradle and haven't had any luck.
