### ISSUE TITLE
Feature request: Builder for Javascript with yarn ?

### ISSUE THREAD

**Issue by pithu** [aws/aws-lambda-builders#669]
### Builder for Javascript with yarn ?

Are there any plans to support an AWS Lambda Build for javascript projects working with yarn ?

In particular, it would be important to guarantee that third-party packages with the same version specified in yarn.lock are packed in lambda when using `sam build`.

If not planned, would it make sense to add a yarn builder in your opinion and would it be difficult? Or is someone aware of a work around?

**Comment by hnnasit** [comment]
Hi @pithu, thanks for the feature request. I will bring this up to the team/PM's to check what their thoughts are. A possible workaround could be to run the custom build workflow, where you can specify how the build will be done. Take a look at the [docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-custom-runtimes.html).

**Comment by pithu** [comment]
@hnnasit Thanks for your quick reply. 

Custom workflow with a Makefile works great and is what i need for my purpose! 

I guess to have ready workflows for the most common node packageManager and bundlers would be probably an overkill anyway, so please feel free to close the ticket.

**Comment by hnnasit** [comment]
Thanks for confirming, that makes sense. Closing this issue, feel free to open a new one if you have any questions.
