### ISSUE TITLE
Feature Request: npm ci support

### ISSUE THREAD

**Issue by jbutz** [aws/aws-lambda-builders#89]
**Description:**

NPM v5.7.0 introduced the [`npm ci`](https://docs.npmjs.com/cli/ci) command, intended for use in automated environments. The main benefit, in my eyes, over `npm install` is that it installs the exact version of packages indicated in the `package-lock.json` file. If you know things worked on your local machine with those dependencies then with the exact same versions things should continue to work elsewhere. `npm ci` also increases the speed of the install due to skipping user oriented features of `npm install`.

My recommendation is that when npm v5.7.0 or above is detected and a `package-lock.json` file is detected then the `npm ci` command is used instead of `npm install`

**Comment by diesal11** [comment]
Any update on this? I'd be happy to look at implementing this

**Comment by sriram-mv** [comment]
@diesal11 Today the workflow choosing process is pretty straightforward per runtime, so if we take in a new workflow, we need to have a way within AWS SAM CLI to be able choose which build workflow we are choosing per runtime, perhaps a env variable, or something within a configuration file? Thoughts?

**Comment by torresxb1** [comment]
Closing as this has already been implemented, see here for an example of how to use: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build.html#examples-npm-ci
